### ISSUE TITLE
Tambahkan dependencies

### ISSUE THREAD

**Issue by r306bsipnk** [r306bsipnk/mbg_194a_catering#1]

**Comment by r306bsipnk** [comment]
tambahkan dependencies sbb:

1.  get
2.  http
3.  image_picker
4.  preference_shared
5.  permission_handler
6.  geolocator
7.  geocoder_plus
8.  flutter_map
9.  flutter_map_dragmarker

**Comment by DivaInCode** [comment]
Sudah dikerjakan Pak. Untuk nomor 4. preference_shared tidak ketemu Pak, adanya shared_preferences.

**Comment by r306bsipnk** [comment]
iya namanya shared_preferences
